### ISSUE TITLE
Driver doesn't handle org.apache.cassandra.db.marshal.DynamicCompositeType

### ISSUE THREAD

**Issue by hkroger** [datastax/ruby-driver#69] opened 2015-04-03 21:54 UTC
Hi,

I have problems with getting the driver to connect to my DSE cluster. I'm getting this:

```
TypeError (nil is not a symbol):
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema/type_parser.rb:134:in `lookup_type'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema/type_parser.rb:103:in `create_type'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema/type_parser.rb:83:in `create_result'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema/type_parser.rb:53:in `parse'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:252:in `create_table'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:91:in `block in update_keyspace'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:89:in `each'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:89:in `each_with_object'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:89:in `update_keyspace'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:72:in `block in update_keyspaces'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:69:in `each'
  cassandra-driver (2.1.3) lib/cassandra/cluster/schema.rb:69:in `update_keyspaces'
  cassandra-driver (2.1.3) lib/cassandra/cluster/control_connection.rb:260:in `block in refresh_schema_async'
  ione (1.2.0) lib/ione/future.rb:348:in `call'
  ione (1.2.0) lib/ione/future.rb:348:in `block in map'
  ione (1.2.0) lib/ione/future.rb:704:in `call'
  ione (1.2.0) lib/ione/future.rb:704:in `call_listener'
  ione (1.2.0) lib/ione/future.rb:743:in `block in resolve'
  ione (1.2.0) lib/ione/future.rb:742:in `each'
  ione (1.2.0) lib/ione/future.rb:742:in `resolve'
  ione (1.2.0) lib/ione/future.rb:787:in `block (2 levels) in initialize'
  ione (1.2.0) lib/ione/future.rb:704:in `call'
  ione (1.2.0) lib/ione/future.rb:704:in `call_listener'
  ione (1.2.0) lib/ione/future.rb:743:in `block in resolve'
  ione (1.2.0) lib/ione/future.rb:742:in `each'
  ione (1.2.0) lib/ione/future.rb:742:in `resolve'
  ione (1.2.0) lib/ione/future.rb:348:in `block in map'
  ione (1.2.0) lib/ione/future.rb:704:in `call'
  ione (1.2.0) lib/ione/future.rb:704:in `call_listener'
  ione (1.2.0) lib/ione/future.rb:743:in `block in resolve'
  ione (1.2.0) lib/ione/future.rb:742:in `each'
  ione (1.2.0) lib/ione/future.rb:742:in `resolve'
  ione (1.2.0) lib/ione/future.rb:29:in `fulfill'
  cassandra-driver (2.1.3) lib/cassandra/protocol/cql_protocol_handler.rb:241:in `complete_request'
  cassandra-driver (2.1.3) lib/cassandra/protocol/v1.rb:155:in `actual_decode'
  cassandra-driver (2.1.3) lib/cassandra/protocol/v1.rb:86:in `decode_header'
  cassandra-driver (2.1.3) lib/cassandra/protocol/v1.rb:64:in `<<'
  cassandra-driver (2.1.3) lib/cassandra/protocol/cql_protocol_handler.rb:271:in `receive_data'
  ione (1.2.0) lib/ione/io/base_connection.rb:162:in `call'
  ione (1.2.0) lib/ione/io/base_connection.rb:162:in `read'
  ione (1.2.0) lib/ione/io/io_reactor.rb:396:in `block in tick'
  ione (1.2.0) lib/ione/io/io_reactor.rb:396:in `each'
  ione (1.2.0) lib/ione/io/io_reactor.rb:396:in `tick'
  ione (1.2.0) lib/ione/io/io_reactor.rb:133:in `block in start'
```

The problem seems to be that the variable "type" is nil because @@types does not contain "org.apache.cassandra.db.marshal.DynamicCompositeType" that "node.name" is referring to.

I don't know what it means or anything but maybe that helps in debugging.

**Comment by avalanche123** [comment] 2015-04-03 21:59
thanks for this, this is a duplicate of https://datastax-oss.atlassian.net/browse/RUBY-102, I'll have a fix for it shortly

**Closed by avalanche123** 2015-04-03 21:59 UTC

**Comment by avalanche123** [comment] 2015-04-03 22:04
try with 969902c7ac33fa9

**Comment by hkroger** [comment] 2015-04-03 22:16
That fixed it! And again, the response and fix was there practically in no time. Unbelievable!

**Comment by avalanche123** [comment] 2015-04-03 22:17
that's how we roll :lollipop:
